### ISSUE TITLE
Adding a Like symbol in the mini player

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#10]
Add a like icon in the mini player to like music faster directly from the lock screen.

If you listen to music and simply want to quickly add the song to your favorites, for example: Favorites. In this case, it would be a great relief and you wouldn't have to take the detour of unlocking the screen to go to the app.

**Comment by dtomvan** [comment]
Did you mean the notification player or the minified player in-app, when browsing your music collection?

**Comment by siggi1984** [comment]
> Did you mean the notification player or the minified player in-app, when browsing your music collection?

I mean the notification player.

**Comment by dtomvan** [comment]
For the former, I suggest taking some inspiration from [musicolet](https://krosbits.in/musicolet/).

**Comment by siggi1984** [comment]
> For the former, I suggest taking some inspiration from [musicolet](https://krosbits.in/musicolet/).
> 
> Edit: screenshot failed to upload Edit2: here it is: https://snipboard.io/uZyI8j.jpg



Yes, the musicolet notification player looks very good.

![Screenshot_20231116-232517_Musicolet](https://github.com/25huizengek1/ViMusic/assets/103368536/fbc83ddb-12cd-46e1-bc9d-4107459f3815)

**Comment by 25huizengek1** [comment]
Great idea, will try to implement when I have the time to.

**Comment by 25huizengek1** [comment]
Finally had the time to implement, was kinda a hassle to mix the database's suspending api with the ~stupid~ mediasessions, but it works now.

Preview:

![image](https://github.com/25huizengek1/ViMusic/assets/50515369/f02d2ef2-e4c7-4978-8a3d-c50f3f78b1d0)

Will be included in the next release.

**Comment by siggi1984** [comment]
I personally think that there should also be a visible Like button somewhere around the player. At the moment it's a bit awkward to use the three dots to get to the hatch button.
![Screenshot_20231120-195045](https://github.com/25huizengek1/ViMusic/assets/103368536/866e11d1-5218-4699-94ce-b5b00de22de8)

**Comment by 25huizengek1** [comment]
That is definitely possible, but I do not know where to put it honestly. Any suggestions?

**Comment by siggi1984** [comment]
> That is definitely possible, but I do not know where to put it honestly. Any suggestions?


Possibly here.
![Screenshot_20231121-060825_1](https://github.com/25huizengek1/ViMusic/assets/103368536/97c48b99-45ea-4c65-bd9a-c64ed3b7ba9d)

**Comment by siggi1984** [comment]
Or maybe here?

![Screenshot_20231121-060825_1](https://github.com/25huizengek1/ViMusic/assets/103368536/aa8a1233-0ff9-4a3a-b89c-b7940f81a1ff)

**Comment by siggi1984** [comment]
The like button in the notification player is still missing

My device: Samsung Galaxy a21s, Android 12

**Comment by 25huizengek1** [comment]
Great, another inconsistency between Android versions. I've tested it on Android 12 and it explains why the service sends a notification with actions, and activates a media session with the same actions.

I've only implemented the media session action for the like, so that explains why it doesn't show up in the 'regular' notification. I'll fix this in a couple hours.

Thank you for reporting this issue, I was not aware as I have only tested the newest version of Android.

**Comment by 25huizengek1** [comment]
![image](https://github.com/25huizengek1/ViMusic/assets/50515369/adc42764-afb1-4791-993e-7db5b5e87cb9)

Thank you for reporting this issue @siggi1984

**Comment by 25huizengek1** [comment]
![image](https://github.com/25huizengek1/ViMusic/assets/50515369/73a00d11-ea0c-4764-ac02-e6d308897685)

Added the like button in the player as well

**Comment by siggi1984** [comment]
The like button in the notification player does not work. You could tap it but nothing happens.

My device Samsung Galaxy A21s, Android 12

**Comment by 25huizengek1** [comment]
Can you please provide me some logs? I do not have a clue why this is happening right now, as it worked well on my Android 12 emulator.

**Comment by siggi1984** [comment]
> Can you please provide me some logs? I do not have a clue why this is happening right now, as it worked well on my Android 12 emulator.

Unfortunately, I don't know how to create a protocol.

**Comment by siggi1984** [comment]
Sorry, must have been my cell phone but it works now.
Thank you very much.
