### ISSUE TITLE
Music hours counting 

### ISSUE THREAD

**Issue by eqoffical** [25huizengek1/ViMusic#110]
My idea is to add a toggle to the settings to enable/disable counting for local music, because now it doesn't seem to be uncounted.
It would also be good to remember the path and name of the song in cases if user restores a backup to avoid duplicates.
Or an even better solution is the ability to manually combining or grouping the hours of songs you've listened to into one.
1. Image of counted music
2. It's also appeals to the top N playlist
<img src="https://github.com/25huizengek1/ViMusic/assets/125155438/ffc48a0d-fd45-45e7-b7b2-eac3361ff890" width=40%> <img src="https://github.com/25huizengek1/ViMusic/assets/125155438/0fac49ff-92b7-4249-92eb-32e91a87b8ff" width=40%>

**Comment by 25huizengek1** [comment]
> One thing I'll love is to have a sum total of playback time on the app at the top of the screen.

Great idea!

@eqofficial What do you mean by 'counting'?

**Comment by eqoffical** [comment]
> > One thing I'll love is to have a sum total of playback time on the app at the top of the screen.
> 
> Great idea!
> 
> @Eqofficial What do you mean by 'counting'?

Sorry for the misunderstanding, the "counting" is shown in the first screenshot
If I understood correctly, the songs are sorted by the number of listens (in hours)

**Comment by genericbetatester** [comment]
> > One thing I'll love is to have a sum total of playback time on the app at the top of the screen.
> 
> Great idea!
> 
> @Eqofficial What do you mean by 'counting'?

It will be good for show off, you can also provide filters for it just like for the top 10. For instance, total number of listening hours this month, this year and all time

**Comment by genericbetatester** [comment]
New update review, everything looks good, I like the Fullscreen lyrics, but ngl it's hard trying to get used to the new play/pause corner roundness. I like the old one better

**Comment by tanmaytez** [comment]
> Btw @25huizengek1 New update looks good, I like the Fullscreen lyrics, but ngl it's hard trying to get used to the new play/pause corner roundness. I like the old one better. Also queue sorting still shows blank space but it retains the position this time it works just as good as the nightly version.

yes I feel the same, and bdw how can I view lyrics in full-screen

**Comment by genericbetatester** [comment]
> > Btw @25huizengek1 New update looks good, I like the Fullscreen lyrics, but ngl it's hard trying to get used to the new play/pause corner roundness. I like the old one better. Also queue sorting still shows blank space but it retains the position this time it works just as good as the nightly version.
> 
> yes I feel the same, and bdw how can I view lyrics in full-screen

Pinch to zoom

**Comment by 25huizengek1** [comment]
> Btw @25huizengek1 New update looks good, I like the Fullscreen lyrics, but ngl it's hard trying to get used to the new play/pause corner roundness. I like the old one better. Also queue sorting still shows blank space but it retains the position this time it works just as good as the nightly version.

The blank space indicates the place the dragged element will animate to when released.

**Comment by 25huizengek1** [comment]
> > > One thing I'll love is to have a sum total of playback time on the app at the top of the screen.
> > 
> > 
> > Great idea!
> > @Eqofficial What do you mean by 'counting'?
> 
> Sorry for the misunderstanding, the "counting" is shown in the first screenshot If I understood correctly, the songs are sorted by the number of listens (in hours)

AFAIK this should just work for Local music? You'll have to sort on playtime as well.

**Comment by eqoffical** [comment]
> AFAIK this should just work for Local music? You'll have to sort on playtime as well.

I wish it should, but I just couldn't find any local music in the "Songs" tab

**Comment by genericbetatester** [comment]
> > Btw @25huizengek1 New update looks good, I like the Fullscreen lyrics, but ngl it's hard trying to get used to the new play/pause corner roundness. I like the old one better. Also queue sorting still shows blank space but it retains the position this time it works just as good as the nightly version.
> 
> The blank space indicates the place the dragged element will animate to when released.

Imo It feels broken with that blank space, It's better if the song doesn't disappear when sorting but I guess it's an issue that you haven't been able to solve, because if I remember correctly, sorting works quite well on classic vimusic.

**Comment by 25huizengek1** [comment]
> > AFAIK this should just work for Local music? You'll have to sort on playtime as well.
> 
> I wish it should, but I just couldn't find any local music in the "Songs" tab

It's located in the Local tab

**Comment by 25huizengek1** [comment]
@genericbetatester No clue what you mean by that, because the reordering works the same as on the original repo.

**Comment by 25huizengek1** [comment]
> > It's located in the Local tab
> 
> Oh, now I see... I thought it should be in one tab, thanks for help ^^

Happy to help. Closing.
