### ISSUE TITLE
Data & memory saver mode

### ISSUE THREAD

**Issue by NeeRaj-2401** [25huizengek1/ViMusic#111]
### Basic

With setting on, user can choose to compromise the audio quality to lowest,  as well as to not load thumbnails at all ( instead use fallback image )

Not loading high quality thumbnails and lowest quality audio, would save data usage and cache storage both,.

### Extended 

This could also be extended to bit complex implementations, such as

1. Set default quality based on network connection ( mobile data, wifi etx )

2. Options to choose the quality amongst all available

3. Load Thumbnail quality or completely disabled 

### Difference?

A single setting to set everything to lowest possible, or giving user full control over what to load and when

**Comment by 25huizengek1** [comment]
I like the idea for omitting the thumbnail loading (I could add thumbnail quality, like max thumbnail size, if you want, as most thumbnails on YouTube support this), but audio quality is still kind of an issue for me. This results in inconsistent behavior, as all cached music will stay in their original quality, even when the current audio quality setting is higher than while caching the music. The only way this could work consistently is by wiping the cache when this quality setting changes.

**Comment by NeeRaj-2401** [comment]
> (I could add thumbnail quality, like max thumbnail size, if you want, as most thumbnails on YouTube support this),

Thats cool as well, in that way, user can enjoy the dynamic theme as well,

**Comment by NeeRaj-2401** [comment]
> as all cached music will stay in their original quality, even when the current audio quality setting is higher than while caching the music

Instead of wiping all cache, can we wipe the cache of current song and replace it with the current streaming quality ( only if streaming quality > already cached quality)
,

**Comment by dtomvan** [comment]
> as all cached music will stay in their original quality

Why not just redownload the higher quality if needed, by a best-guess bitrate comparison? When we want to save space maybe we could introduce some cleanup page, in which the user can delete the LRU cache parts, or is that how the cache works already? Then some more granularity in the cache limit could be an advantage.

**Comment by NeeRaj-2401** [comment]
> > (I could add thumbnail quality, like max thumbnail size, if you want, as most thumbnails on YouTube support this),
> 
> Thats cool, in that way, user can enjoy the dynamic theme as well,

But also keep the fallback thumbnails options, because in local music section i noticed alot of songs dont have thumbnails themselves, in such cases the fallback image would also be useful, and obviously in data saver mode as discussed earlier

**Comment by 25huizengek1** [comment]
Added in Settings ==> Other ==> Dynamic Thumbnails

**Comment by NeeRaj-2401** [comment]
Thank you for the prompt response, @25huizengek1 . I appreciate the quick fix.

I've noticed a minor issue in the current implementation. Choosing a slider value between 16 and 2160 may result in reduced precision. It would be great to enhance this by adding a number input or presets( like wavy bar and thumbnail roundness ), ensuring consistency in the UI. Appreciate your work on implementing the requested feature.

**Comment by 25huizengek1** [comment]
Good idea, I'll see when I have the time to implement this in a way that makes sense.
