### ISSUE TITLE
Player: Music cover image doesn't show up while offline

### ISSUE THREAD

**Issue by vedxp** [25huizengek1/ViMusic#113]
### Steps to reproduce the bug

- Download any song
- Turn off the internet/mobile data
- Play the downloaded song

### Expected behavior

The music cover/thumbnail should be displayed as it does when the app have internet access.

### Actual behavior

The cover doesn't show up, regardless that the song has been downloaded for offline listening.

### Screenshots/Screen recordings

![Screenshot_20240213-085009](https://github.com/25huizengek1/ViMusic/assets/87353286/e091fea2-15ba-4291-aa8c-5f69459e3806)

### ViMusic version

0.6.4

### Android version

Android 13

**Comment by genericbetatester** [comment]
Did you pre-cache, or did you stream the song before pre-cache, If it's the former, the album art won't show up unless you click and play the song.

**Comment by vedxp** [comment]
> Did you pre-cache, or did you stream the song before pre-cache, If it's the former, the album art won't show up unless you click and play the song.

None of them, I downloaded the whole playlist and then played the song turning the mobile data off.

**Comment by 25huizengek1** [comment]
Not a bug: when the app shows a thumbnail it loads one specifically for the size of the thumbnail in de UI. This is intended behavior, because loading all thumbnail sizes at once is just too inefficient and will take way too long while (pre-)caching, while also wasting network resources and possibly wasting storage.

**Comment by vedxp** [comment]
> Not a bug: when the app shows a thumbnail it loads one specifically for the size of the thumbnail in de UI. This is intended behavior, because loading all thumbnail sizes at once is just too inefficient and will take way too long while (pre-)caching, while also wasting network resources and possibly wasting storage.

@25huizengek1 any possibility of adding an option to fetch all the thumbnail sizes of songs downloaded?
