### ISSUE TITLE
Download Manager: Show the download status of playlist

### ISSUE THREAD

**Issue by vedxp** [25huizengek1/ViMusic#114]
## Feature request: Show the download status of playlist instead of individual song

As of current implementation, when a user starts downloading a playlist, there's no information about the download status/progress of the playlist, like how many songs has been downloaded and how many are remaining.

It just shows a horizontal progress bar at the top for each song until the whole playlist is downloaded.

**Comment by Syntax-Err5** [comment]
This was explained in #84
It's just more consistent to have an indeterminate (not showing download progress) bar than showing the progress. It won't affect the functionality of the app.

**Comment by 25huizengek1** [comment]
Thank you @Syntax-Err5 for the explanation. While you could just turn on the notification for a progress bar, I’m currently not going to implement this, please see #84
