### ISSUE TITLE
Songs and Videos suggestions not loading via search

### ISSUE THREAD

**Issue by Malgotra** [25huizengek1/ViMusic#115]
### Steps to reproduce the bug

1. Open ViMusic.
2. Search any artist or song.
3. Search suggestions are not fully loading.
4. Only few songs and videos are loading.
5. Takes too much time to show more suggestions.

### Expected behavior

On searching songs and videos via search it should load full suggestions like in YouTube music.

### Actual behavior

Not loading suggestions fully.

### Screenshots/Screen recordings

![Screenshot_20240217-153216](https://github.com/25huizengek1/ViMusic/assets/122884037/a94eca3b-6351-41d4-b23c-1717691a80c1)
![Screenshot_20240217-153206](https://github.com/25huizengek1/ViMusic/assets/122884037/be3c4bad-cf21-4162-8039-82079c4cc608)

### ViMusic version

v.0.6.4

### Android version

Android 13

### Additional information

Motorola Moto G72 (Android 13)
Try with mobile data and WiFi both.

**Comment by Malgotra** [comment]
It takes too much time to load next suggestions.

**Comment by 25huizengek1** [comment]
What do you mean exactly with this? The loading entirely depends on YouTube's servers, so there is no way for me to speed this up.

**Comment by Malgotra** [comment]
Thanks you for your reply. I downloaded RiMusic which is also fork of ViMusic and test this test bug. In RiMusic it works totally fine. Songs and videos loading with out any problem.

**Comment by 25huizengek1** [comment]
I don't understand? What is the difference here?

**Comment by Malgotra** [comment]
I'm posting a recording. Hope you understand my issue. 
https://drive.google.com/file/d/1--6xmI0A7N1IJkQh-MUNukssrDJg6846/view?usp=drivesdk

**Comment by 25huizengek1** [comment]
I apologise, I messed the loading state up while refactoring in d417339f8c1fdf9fae564844fc9f482e01c21dfb, it works again for every search tab.
