### ISSUE TITLE
Amoled Black mode for Dynamic theme

### ISSUE THREAD

**Issue by SiddhantRakh** [25huizengek1/ViMusic#116]
### I suggest implementing an optional AMOLED black background that preserves the dynamic theme's colors. 

The current PureBlack theme's black background reduces UI visibility by replacing subtle grey button overlays. I propose a colored background tint for the Now Playing screen with AMOLED black elsewhere, as an optional setting. 
The Innertune app exemplifies this concept effectively. I have attached some screenshots for a visual representation for how this should be implemented. 
(App: Innertune)
![Screenshot_20240218-152528_InnerTune](https://github.com/25huizengek1/ViMusic/assets/42494931/0633ccec-e0cc-4535-b61e-347062493386)
![Screenshot_20240218-152535_InnerTune](https://github.com/25huizengek1/ViMusic/assets/42494931/c9d19848-2335-4deb-834f-f855c102a10c)

**Comment by dtomvan** [comment]
So you want everything black, except for the player tray itself?! Doesn't make sense to me...

**Comment by 25huizengek1** [comment]
I personally think this is a good idea, as an optional toggle though.

**Comment by 25huizengek1** [comment]
Added, this is what it looks like right now:

**Dynamic:**
<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/1a66e215-97f9-468e-ab30-3d6437204fb5" width="30%" />

**AMOLED:**
<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/82d013fb-8a57-4c9f-ac56-28dd6c244ebf" width="30%" />

**PureBlack:**
<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/83c8c2d9-5515-4422-b81f-1e7e6de407c6" width="30%" />

**Comment by SiddhantRakh** [comment]
Wow! Exactly like I wanted. Thanks for implementing it and more so for this fast. Eagerly waiting for the new update now. I am a sucker for nicely amoled themed great apps.
