### ISSUE TITLE
Dynamic thumbnail 

### ISSUE THREAD

**Issue by walker-11** [25huizengek1/ViMusic#117]
## Feature request: Dynamic thumbnail When playing Music from YouTube Video 

- Please Add Dynamic thumbnail for music when playing from YouTube Videos like  below mentioned screenshot for reference 
 
screenshot from blackhole open source music app for reference

<img src="https://github.com/25huizengek1/ViMusic/assets/151006009/9143769b-16f9-46a7-aeba-ed4e3936d077" width="30%" />

screenshot compared to Vi music

<img src="https://github.com/25huizengek1/ViMusic/assets/151006009/01c7b223-61a8-451d-8d65-6a922afac4bf" width="30%" />

- Please Improve thumbnail Quality in QS Panel , For reference I mentioned below screenshots to compare as you can see major difference in Thumbnail quality 

screenshot from Vi music

<img src="https://github.com/25huizengek1/ViMusic/assets/151006009/dc424ad4-c790-4b9b-a011-6dafac033894" width="30%" />

screenshot from blackhole music to compare

<img src="https://github.com/25huizengek1/ViMusic/assets/151006009/436c1b59-7b27-40ca-b7b4-6fae8c02641d" width="30%" />

Above Mentioned Feedback May improve your App 🤗

Love you for Hard work and creative 🩷

@25huizengek1

**Comment by 25huizengek1** [comment]
Thank you for your appreciation, great suggestions!

I'll try to implement these features soon 👍

**Comment by 25huizengek1** [comment]
As you may have noticed I already cranked up the quality of the thumbnails (you can adjust it yourself too) but it seems like I can't get it perfectly right (YouTube is not that consistent with their cdns etc.) so my perfectionistic brain now really wants to keep it how it is right now 😅

**Comment by walker-11** [comment]
I really Appreciate to your work
