### ISSUE TITLE
Improvement of the search function in the songs area

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#12]
### Steps to reproduce the bug

At the moment, the search function only filters by song name.

When I search for an artist name, nothing is found.

### Expected behavior

The search function should filter by song name and at the same time by artist name.

### Actual behavior

*

### ViMusic version

0.5.7

### Android version

Android 12

**Comment by 25huizengek1** [comment]
On the to do list. Seems like a good idea, don't know about performance though.

**Comment by 25huizengek1** [comment]
Thank you for your suggestion, will be included in v0.5.9
