### ISSUE TITLE
KLWP and KWGT support

### ISSUE THREAD

**Issue by dainvincible1** [25huizengek1/ViMusic#13]
KLPW and KWGT to detect ViMusic as a music player

**Comment by 25huizengek1** [comment]
Thank you for your suggestion, but I'll need a bit more information. What do you mean by KLWP and KWGT support? For example for KWGT, is there some widget you want to have support for?

**Comment by dainvincible1** [comment]
> Thank you for your suggestion, but I'll need a bit more information. What do you mean by KLWP and KWGT support? For example for KWGT, is there some widget you want to have support for?

Yes support in music widgets in kwgt. Right now KWGT doesnt detect ViMusic as a music player thats why when i play a song the KWGT music widget doesnt show the song info in the widget

**Comment by 25huizengek1** [comment]
As far as I'm concerned, the music played by ViMusic is already being recognized by KWGT. Could you please show me an example of a preset not working as expected, or something else so I can investigate this further?

**Comment by dainvincible1** [comment]
> As far as I'm concerned, the music played by ViMusic is already being recognized by KWGT. Could you please show me an example of a preset not working as expected, or something else so I can investigate this further?


https://github.com/25huizengek1/ViMusic/assets/127825700/fa05bfd8-7185-4fb3-83de-ce260046b0d6

![image](https://github.com/25huizengek1/ViMusic/assets/127825700/5607df5a-5f56-4beb-8acc-9a1c043ac66e)

**Comment by 25huizengek1** [comment]
I don't know what is happening on your device, but on my end it works perfectly fine:

![Screenshot_20231122_180701_Kustom Widget.png](https://github.com/25huizengek1/ViMusic/assets/50515369/3a4001f1-f83e-4378-aa25-280b61466333)

Very strange, are you using the [latest version](https://github.com/25huizengek1/ViMusic/releases/latest) of ViMusic?

**Comment by dainvincible1** [comment]
> I don't know what is happening on your device, but on my end it works perfectly fine:
> 
> ![Screenshot_20231122_180701_Kustom Widget.png](https://user-images.githubusercontent.com/50515369/284983707-3a4001f1-f83e-4378-aa25-280b61466333.png)
> 
> Very strange, are you using the [latest version](https://github.com/25huizengek1/ViMusic/releases/latest) of ViMusic?

Sorry i didnt see the latest release. im using the previous version of that. But im not able to download 0.5.8 verison since there is no apk file (sorry im a noob and i dont know how to install app from the source code). If possible please also add the apk file in the next release

**Comment by siggi1984** [comment]
> > I don't know what is happening on your device, but on my end it works perfectly fine:
> > ![Screenshot_20231122_180701_Kustom Widget.png](https://user-images.githubusercontent.com/50515369/284983707-3a4001f1-f83e-4378-aa25-280b61466333.png)
> > Very strange, are you using the [latest version](https://github.com/25huizengek1/ViMusic/releases/latest) of ViMusic?
> 
> Sorry i didnt see the latest release. im using the previous version of that. But im not able to download 0.5.8 verison since there is no apk file (sorry im a noob and i dont know how to install app from the source code). If possible please also add the apk file in the next release

https://25huizengek1.github.io/fdroid-repo/fdroid/repo/

Add this repo to fdroid and you can install the new version

**Comment by dainvincible1** [comment]
> > > I don't know what is happening on your device, but on my end it works perfectly fine:
> > > ![Screenshot_20231122_180701_Kustom Widget.png](https://user-images.githubusercontent.com/50515369/284983707-3a4001f1-f83e-4378-aa25-280b61466333.png)
> > > Very strange, are you using the [latest version](https://github.com/25huizengek1/ViMusic/releases/latest) of ViMusic?
> > 
> > 
> > Sorry i didnt see the latest release. im using the previous version of that. But im not able to download 0.5.8 verison since there is no apk file (sorry im a noob and i dont know how to install app from the source code). If possible please also add the apk file in the next release
> 
> https://25huizengek1.github.io/fdroid-repo/fdroid/repo/
> 
> Add this repo to fdroid and you can install the new version

thanks. its done

**Comment by 25huizengek1** [comment]
> Sorry i didnt see the latest release. im using the previous version of that. But im not able to download 0.5.8 verison since there is no apk file (sorry im a noob and i dont know how to install app from the source code). If possible please also add the apk file in the next release

I forgot 💀 

It's up now: https://github.com/25huizengek1/ViMusic/releases/tag/v0.5.8

**Comment by 25huizengek1** [comment]
Could you try again and check if it's still not showing in KWGT?

**Comment by dainvincible1** [comment]
> Could you try again and check if it's still not showing in KWGT? @dainvincible1

After uninstalling and installing both the apps, now ViMusic is being detected as a music player in KWGT but the album cover is not showing in the widget


https://github.com/25huizengek1/ViMusic/assets/127825700/d85a999a-f860-4117-82d1-87df1b9a1f35

**Comment by 25huizengek1** [comment]
On my phone that also works perfectly fine. Can you please provide me with the widget you are using? Because my KWGT widget uses the `$mi(cover)$` formula, which recognizes the album cover. Maybe your widget uses a different formula, so I can investigate why your widget doesn't show anything for the album cover.

**Comment by dainvincible1** [comment]
> On my phone that also works perfectly fine. Can you please provide me with the widget you are using? Because my KWGT widget uses the `$mi(cover)$` formula, which recognizes the album cover. Maybe your widget uses a different formula, so I can investigate why your widget doesn't show anything for the album cover.

The widget i used was "pastel widget". I tried different widgets too but same issue exists

**Comment by 25huizengek1** [comment]
Alright, but what version of Android are you using? Because below Android 13, you have to enable "Show song cover" in the Appearance settings to let other apps recognize album covers from ViMusic. If the option is visible for you in the settings you are on Android 12 or lower, so if that is visible for you, try turning it on and see if that works.

**Comment by dainvincible1** [comment]
> Alright, but what version of Android are you using? Because below Android 13, you have to enable "Show song cover" in the Appearance settings to let other apps recognize album covers from ViMusic. If the option is visible for you in the settings you are on Android 12 or lower, so if that is visible for you, try turning it on and see if that works.

woow thanks you. it works well now. it was cause i didnt enable the option. thanks

**Comment by 25huizengek1** [comment]
No problem, closing as the issue has been resolved.
