### ISSUE TITLE
Songs not loading in the latest version of the app 0.6.5, I'm not using any VPN , or Custom DNS also I tried to old version app 0.6.4 I'm facing same issues 🥹

### ISSUE THREAD

**Issue by walker-11** [25huizengek1/ViMusic#133]
![Screenshot_20240227-050306_ViMusic.png](https://github.com/25huizengek1/ViMusic/assets/151006009/9556c295-49bb-4304-a576-9f4fb2a87933)

![Screenshot_20240227-050329_ViMusic.png](https://github.com/25huizengek1/ViMusic/assets/151006009/5e42fa50-8511-491e-96e3-a0d92f060c26)

**Comment by 25huizengek1** [comment]
Superseded by #134
