### ISSUE TITLE
songs not loading 

### ISSUE THREAD

**Issue by walker-11** [25huizengek1/ViMusic#134]
### Steps to reproduce the bug

Go to search bar and search song

### Expected behavior

Songs have to load

### Actual behavior

Songs are not loading 

### Screenshots/Screen recordings

![Screenshot_20240227-050306_ViMusic](https://github.com/25huizengek1/ViMusic/assets/151006009/04208361-2ca3-4354-9613-17a67171b4e3)
![Screenshot_20240227-050329_ViMusic](https://github.com/25huizengek1/ViMusic/assets/151006009/c9780b7f-b9ba-4dc6-8f94-b52c3e6e95da)

### Logs

[27_02-05-16-03_639.log](https://github.com/25huizengek1/ViMusic/files/14412512/27_02-05-16-03_639.log)

### ViMusic version

v0.6.5

### What kind of build are you using?

Release (GitHub / F-Droid)

### Android version

Android 14 

### Device info

I'm using redmi note 10s running Evolution X custom ROM Android 14 

### Checklist

- [X] I am able to reach YouTube Music through the **official** app/website and can confirm that I live in a [supported country](https://support.google.com/youtubemusic/answer/6313540?hl=en) (and this country is not temporarily unavailable)
- [X] I am not using a proxy, VPN, device policy or anything else that restricts access to YouTube Music
- [X] This issue has not been submitted already (this is not a duplicate of another issue)
- [X] This issue is also reproducible with [vfsfitvnm/ViMusic](https://github.com/vfsfitvnm/ViMusic) (optional)

**Comment by 25huizengek1** [comment]
Very strange, will look at the logs.

**Comment by 25huizengek1** [comment]
The culprit:

```json
{
  "error": {
    "code": 400,
    "message": "Request contains an invalid argument.",
    "errors": [
      {
        "message": "Request contains an invalid argument.",
        "domain": "global",
        "reason": "badRequest"
      }
    ],
    "status": "INVALID_ARGUMENT"
  }
}
```

**Comment by 25huizengek1** [comment]
This means this is the exact same issue as #90, will continue the conversation over there.

**Comment by walker-11** [comment]
> This means this is the exact same issue as #90, will continue the conversation over there.

Ok thanks 👍 but I don't know what happened now but this bug is not present in v0.6.4 version app
