### ISSUE TITLE
Download function

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#16]
Would it be possible to add a download function for songs, playlists and albums.

The app already has a cache function - maybe you can use it for the download function somehow.

**Comment by 25huizengek1** [comment]
What do you mean by 'download function'? When you listen to songs they already get downloaded and cached.

**Comment by siggi1984** [comment]
I'll try to explain it with an example: Suppose I'm traveling and have no internet on the road, then I could only listen to the songs that are stored in the cache. But if I could download a collection of songs beforehand, that would be very advantageous.

It would also be fine if you could only play the downloaded songs in ViMusic. After all, the app is not a download app, but a music streaming app.

**Comment by 25huizengek1** [comment]
If I understand you correctly, I think you want functionality to pre-cache the songs, instead of having to listen to all of them beforehand?

**Comment by siggi1984** [comment]
> If I understand you correctly, I think you want functionality to pre-cache the songs, instead of having to listen to all of them beforehand?

Yes, that's exactly what I mean, download the songs individually and it would be cool to have a download button in the playlists and albums that you tap on and the whole playlist or album is downloaded and a second button in download to remove.

**Comment by Enigma1309** [comment]
hey there exists a ViMusic Fork that have this feature already could you implement it?
https://github.com/fast4x/RiMusic

**Comment by 25huizengek1** [comment]
Started working on this feature. I got it working, it is somewhat stable, so I think I’ll push the progress today. The only thing missing is the download progress, but I think the download notification is sufficiënt. A progress bar can be nice, but it may clutter the UI too much, so I’m still considering this

**Comment by Enigma1309** [comment]
Thanks for working on this ✨

**Comment by 25huizengek1** [comment]
I think this feature is done. If you have any further questions, please reopen.

**Comment by siggi1984** [comment]
However, the download does not always work reliably. Sometimes the app crashes when you tap the download button. 

Sometimes the app crashes and then downloads the songs in the background.

Sometimes nothing happens when you tap the download button.


https://github.com/25huizengek1/ViMusic/assets/103368536/7da65730-c3b5-4eb2-b93a-b199569114de

**Comment by 25huizengek1** [comment]
This is exactly the testing I needed (it's the reason why I haven't released a new version yet!), thank you for that.

I should just be able to catch the exceptions (which I thought I already did), but let me try to fix this.
