### ISSUE TITLE
Error in the search function

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#17]
### Steps to reproduce the bug

The search function in the local area is not working properly.

You search for a song or artist but something else is played.

See video.

### Expected behavior

*

### Actual behavior

*

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/103368536/183e49f7-40e1-4a1e-9711-58916968b140

### ViMusic version

0.5.9

### Android version

Android 12

**Comment by siggi1984** [comment]
Just noticed that the search function in the song area has the same error.

**Comment by 25huizengek1** [comment]
Let's just say this search function was a fancy way of showing the songs filtered but playing the playlist as if it wasn't filtered. Fixed it, and as a bonus I made the keyboard disappear when you play the song, for convenience.
