### ISSUE TITLE
App language

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#20]
I would like to use the app in my language.

If you wish, I would also translate it if you provide me with the file for translation.

**Comment by 25huizengek1** [comment]
ViMusic currently doesn't use language strings in Android, so the app is not translatable at the moment. In the future I'll refactor this when I have the time to.

**Comment by siggi1984** [comment]
Okay, then I'll wait patiently.

**Comment by 25huizengek1** [comment]
I've added all text to [app/src/main/res/values/strings.xml](https://github.com/25huizengek1/ViMusic/blob/master/app/src/main/res/values/strings.xml), or at least I hope so. Please let me know if I missed anything.

The app can now be translated, so if you want to help translate, please do so by translating the strings in strings.xml and opening a pull request. Closing for now, please let me know if you have any further questions.

**Comment by siggi1984** [comment]
Okay great, I'll translate it in the next few days.
