### ISSUE TITLE
If i search a song from "song section" then it plays other song

### ISSUE THREAD

**Issue by dainvincible1** [25huizengek1/ViMusic#21]
### Steps to reproduce the bug

Search for a song from the "song" section 
it plays other song

### Expected behavior

it should play the exact song

### Actual behavior

when i search for a song it plays other song

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/127825700/b7830e63-ac46-4de6-9c7d-f55ac47fcec6

### ViMusic version

latest version

### Android version

android 11

**Comment by 25huizengek1** [comment]
No problem, it has indeed been fixed since #17. I do not know when I'll release, since the release schedule has been sort of random at the moment.
