### ISSUE TITLE
App not Working

### ISSUE THREAD

**Issue by Enigma1309** [25huizengek1/ViMusic#23]
### Steps to reproduce the bug

`

### Expected behavior

`

### Actual behavior

`

### Screenshots/Screen recordings

`

### Logs

`

### ViMusic version

Latest commit 

### Android version

Andorid 8

### Additional information

Device :-Moto G4 +
Android :- Oreo 8

this app isn't able to install via package manager while unforked official app works on my device
while installing package manager shows app not installed :(

**Comment by 25huizengek1** [comment]
I don't know what could cause that, but can you give me some information about the APK you used to try and install the app?

The latest commit has not yet been released by me, so please try installing the latest release by either [downloading the APK directly from GitHub releases](https://github.com/25huizengek1/ViMusic/releases/latest) or by [using the F-Droid repository](https://25huizengek1.github.io/fdroid-repo/fdroid/repo)

**Comment by Enigma1309** [comment]
i'm using github repo for the release v0.5.9

**Comment by Enigma1309** [comment]
btw i have old (aka official) version of vi music preinstalled

**Comment by 25huizengek1** [comment]
Because I signed the app with my key, that is unfortunately not possible, but you could export / backup your database in the old ViMusic version, uninstall it, and then install my version, as the database of my fork is fully compatible with the official version of ViMusic.

**Comment by Enigma1309** [comment]
> Because I signed the app with my key, that is unfortunately not possible, but you could export / backup your database in the old ViMusic version, uninstall it, and then install my version, as the database of my fork is fully compatible with the official version of ViMusic.

okay if i do so will i be able to retain all my existing offline songs?
if no, do i even have to consider switching to it? and what benefits would i get over official fork ?

**Comment by 25huizengek1** [comment]
You won't because the offline songs are considered _cache_, so they will be deleted by the Android system when you delete the app. Since the original version of ViMusic doesn't have functionality for exporting said cache, you can't keep the cache even if you wanted to.

I also cannot build this fork in a way that you can just update the app, since this fork is not signed/trusted by vfsfitvnm. So unfortunately I do not have a workaround for this right now. In the future, I'll probably make a nightly build. This build will have a different application ID, handy for testing, but also useful for this use case. It can be installed while there is already a regular version of ViMusic installed.

**Comment by 25huizengek1** [comment]
Benefits of switching are in a nutshell: more features, more active support (vfsfitvnm retired from maintaining ViMusic a few months ago), crashes and inconsistencies fixed. I've also started support for different languages today, so maybe that is something you are interested in.

**Comment by Enigma1309** [comment]
> more features
What do you actually mean by more features?? 
Your readme.md looks same as official please consider making/updating one for your project and your features
also i'm considering to switch this branch due to inactive developement

**Comment by 25huizengek1** [comment]
In README.md I've actually added a few major new features in [this commit](https://github.com/25huizengek1/ViMusic/commit/b80b38dd759130b8eaa4d191fb3ad20bfcafdde0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5)

Closing, as the nightly build is now available in my F-Droid repository. This build works even when the official app is still installed. You can add my F-Droid repository [here](https://25huizengek1.github.io/fdroid-repo/fdroid/repo)
