### ISSUE TITLE
Quick picks based on last song played

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#26]
Most of the time, the quick picks are not based on the last song played. It would be better if the quick picks were based on the last song played.

Even better would be a selection option like Harmony Music, see screenshot.
I think the quick picks are very successful.

![Screenshot_20231203-163553](https://github.com/25huizengek1/ViMusic/assets/103368536/502c9bf9-0fc1-424e-9855-7da1cb8c4ede)

**Comment by 25huizengek1** [comment]
Implemented, will be included in the next release. Thank you for your suggestion, @siggi1984

**Comment by 25huizengek1** [comment]
@tanmaytez Moving to another issue
