### ISSUE TITLE
Playlist not loading

### ISSUE THREAD

**Issue by brnwlshubh** [25huizengek1/ViMusic#28]
### Steps to reproduce the bug

Go to "Discover"
Choose any "Moods and Genres" option
Then Choose any Playlist
It doesn't load properly.

### Expected behavior

It should be open to play any song.

### Actual behavior

It doesn't load playlist (some)

### Screenshots/Screen recordings

![Screenshot_20231206_140333](https://github.com/25huizengek1/ViMusic/assets/77489594/1c9b1272-aa95-4ee2-94d3-b5a51fb10481)

### ViMusic version

0.5.10 latest build(6/12/23)

### Android version

Android 13

**Comment by 25huizengek1** [comment]
I can unfortunately not reproduce this. Which mood/playlist are you trying to load?

**Comment by brnwlshubh** [comment]
Almost all are not loading... Only some are perfectly loading

**Comment by brnwlshubh** [comment]
> Which mood/playlist are you trying to load?

Haryanvi,Punjabi,Hindi,Indian Pop,Workout,etc.
All are not loading

**Comment by 25huizengek1** [comment]
Can I ask you what language your device is using? Maybe YouTubes internal api doesn't recognize it. On my device both nightly and release work just fine for these moods

**Comment by brnwlshubh** [comment]
> Can I ask you what language your device is using?
English(US)

**Comment by brnwlshubh** [comment]
@25huizengek1 Restarting the device & changing the device language doesn't fixes the issue.

**Comment by 25huizengek1** [comment]
> Same issue is reported by other users also
> 1. https://github.com/fast4x/RiMusic/issues/178
> 2. https://github.com/fast4x/RiMusic/issues/111

Was aware, thought I fixed it. And it should still work in the release build instead of nightly?

**Comment by 25huizengek1** [comment]
> Can you try [this](https://music.youtube.com/playlist?list=RDCLAK5uy_kuo_NioExeUmw07dFf8BzQ64DFFTlgE7Q )?

Thank you, with this playlist I can reproduce the issue. Will investigate later.

**Comment by brnwlshubh** [comment]
> Was aware, thought I fixed it. And it should still work in the release build instead of nightly?

Currently I'm using nightly only, will try release too...to check this.

**Comment by 25huizengek1** [comment]
Fixed it, will be available in the next nightly build.

Here's what that playlist looks like right now:
<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/4589aa70-73bf-4682-a1c2-938a02703d7b" width="30%" />

Thank you so much for noticing this, @brnwlshubh

**Comment by brnwlshubh** [comment]
@25huizengek1 Is this fix included in today's nightly build?

**Comment by 25huizengek1** [comment]
Thanks to the OOM killer the build got cancelled again, so I've manually triggered a nightly build now. It should be up in a few minutes.

**Comment by brnwlshubh** [comment]
@25huizengek1 Working Fine for me😊
