### ISSUE TITLE
Old Player UI?

### ISSUE THREAD

**Issue by Enigma1309** [25huizengek1/ViMusic#29]
Is there any way to turn off the new player and switch back to old one (official fork)

I really didn't liked the position of like and previous buttons in the player 
Could you swap the places of those (like and prevoius button) since it's causing the design inconsistency. (or rather add an option to switch to old player in the app itself).
Reference below
![image](https://github.com/25huizengek1/ViMusic/assets/94917588/59a126f8-ebce-4a6e-84a9-d1a05fae849b)

Also could you control the button roundness via the thumbnail Roundness option , cause it's causing issues on devices with smaller screen

![image](https://github.com/25huizengek1/ViMusic/assets/94917588/ad6cc8bf-62db-4168-8868-941f0a4c537c)

Thanks I've finally switched to this fork

**Comment by 25huizengek1** [comment]
Definitely possible. I think its a bit strange that the UI is that bad on small screens, but I'll look into it. What is the Device/Model and screen resolution you are using in the second screenshot?

**Comment by 25huizengek1** [comment]
- [ ] Add switch for 'New UI'
- [ ] Fix player UI not looking correct on smaller screens

**Comment by Enigma1309** [comment]
> Definitely possible. I think its a bit strange that the UI is that bad on small screens, but I'll look into it. What is the Device/Model and screen resolution you are using in the second screenshot?

While taking second screen shot i was using MotoG4+ with a low dpi setting (to exaggerate the effect overall) but it does come up quite inconsistent when using app in split screen

**Comment by 25huizengek1** [comment]
Added old control UI back, available in the next version and in nightly builds. Enable in settings: Appearance > Player > Player layout

Should be more suitable for smaller screens / low dpi. If it doesn't, let me know.

**Comment by Enigma1309** [comment]
thanks

**Comment by Enigma1309** [comment]
Could You add the option to Enable/disable wavy timeline in Appearance tab
This will enable/disable wavy timeline in both modern and classical player.

**Comment by 25huizengek1** [comment]
![image](https://github.com/25huizengek1/ViMusic/assets/50515369/93496fac-e613-4e3d-b3a5-e8f5178b385f)

Added in e677f1fed09c02aed42b71fd2d83fb5f2978d912

**Comment by Enigma1309** [comment]
Thanks ❤️

**Comment by 25huizengek1** [comment]
Just a heads up: I've made a mistake with the wavy bar, fixed it but its not in today's build, so keep that in mind.
