### ISSUE TITLE
Stop music playback when app is closed and cleared from recent tasks

### ISSUE THREAD

**Issue by dainvincible1** [25huizengek1/ViMusic#3]
## Feature request: [name]

A setting to stop music playback when app is closed and cleared from recent tasks. A toggle option will be great. Something like this 

![image](https://github.com/25huizengek1/ViMusic/assets/127825700/b9f19fbc-8f21-4d25-9e9a-3dca07deca6f)

or

![image](https://github.com/25huizengek1/ViMusic/assets/127825700/50c666ea-73a7-4b3a-9942-fad250499f26)

**Comment by 25huizengek1** [comment]
The player service already stops when you paused the music, but as a setting to always stop the player, I think it makes sense. Implemented in 369b40bc0c61e4b05851aacff56f24667035e0ac

**Comment by 25huizengek1** [comment]
Will be included in v0.5.6
