### ISSUE TITLE
Probable bug: YouTube Music liked playlist is not getting imported correctly

### ISSUE THREAD

**Issue by 25huizengek1** [25huizengek1/ViMusic#30]
> @25huizengek1 I've noticed that the songs in the playlists are limited to 77, as I've imported my liked songs which are over 1k. Is there any way to fix this?

> I mean, I have the playlist of yt music in which the playlist has over 1k songs. When I imported it to vi music via opening links, it only got the 77 songs out of 1k+ songs.

<img src="https://github.com/25huizengek1/ViMusic/assets/132748284/7c892b87-057b-4a67-a366-abbe344be11d" width="30%" />

> This playlist has over a thousand songs

<img src="https://github.com/25huizengek1/ViMusic/assets/132748284/9dd46761-44e0-415e-be0c-4ed526215eb5" width="30%" />

> And here is the imported playlist of it to vi music, which only has 77 songs of the playlist.

_Originally posted by @tanmaytez in https://github.com/25huizengek1/ViMusic/issues/27#issuecomment-1843558038_
            
---

As pointed out in https://github.com/25huizengek1/ViMusic/issues/27#issuecomment-1843978381, I personally can't reproduce. Thank you @tanmaytez for pointing this out though, as I want to make the app as stable as possible.

Can you please elaborate further on how this works? I personally do not have a share button for 'Liked Music' in the official YouTube Music app.

**Comment by tanmaytez** [comment]
Uhm yes initially we can't share liked music. We should first make the liked music public then we'll get an option to share or will be able to make the liked music a seperate playlist then share it.

I think the playlist import is only upto 77 songs. It doesn't matter if it's liked music playlist or not

**Comment by 25huizengek1** [comment]
Do you have a link for me of a broken playlist, so I can test it and investigate?

**Comment by tanmaytez** [comment]
> Do you have a link for me of a broken playlist, so I can test it and investigate?

https://music.youtube.com/playlist?list=PLAh7mNuiZaPveidx7gBqqaHX5JJIhI-Sx

**Comment by 25huizengek1** [comment]
Unfortunately, I cannot reproduce this issue. I am able to load 923 songs of the 1138, because a lot of songs are not available (at least for me in my country, even using the official player on music.youtube.com)

**Comment by tanmaytez** [comment]
> Unfortunately, I cannot reproduce this issue. I am able to load 923 songs of the 1138, because a lot of songs are not available (at least for me in my country, even using the official player on music.youtube.com)

Did u get 923 songs in yt music or vi music?

I think there's a limit to importing the songs in a part of code( I don't know anything about it)

**Comment by 25huizengek1** [comment]
In ViMusic I get 923 songs. In YouTube music in the browser all songs are visible, but a lot of them are greyed out, which is causing ViMusic to only load 923 of them.

<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/8866f1e8-534f-426a-bd61-bafb012ce928" width="30%" />
<img src="https://github.com/25huizengek1/ViMusic/assets/50515369/0791f432-3988-4e5b-8ffc-f3c86abbb173" width="30%" />

![image](https://github.com/25huizengek1/ViMusic/assets/50515369/1a2b5d74-c7b7-4d4b-a8bd-770d0b8a0921)

**Comment by tanmaytez** [comment]
> In ViMusic I get 923 songs. In YouTube music in the browser all songs are visible, but a lot of them are greyed out, which is causing ViMusic to only load 923 of them.
> 
> <img src="https://github.com/25huizengek1/ViMusic/assets/50515369/8866f1e8-534f-426a-bd61-bafb012ce928" width="30%" />
> <img src="https://github.com/25huizengek1/ViMusic/assets/50515369/0791f432-3988-4e5b-8ffc-f3c86abbb173" width="30%" />
> 
> ![image](https://github.com/25huizengek1/ViMusic/assets/50515369/1a2b5d74-c7b7-4d4b-a8bd-770d0b8a0921)
> 
> 

Are u able to get 923 songs after fixing the issue?

It means the bug has been fixed. The grayed out songs are either removed or can't play in vimusic or yt music.. only playable in YouTube

**Comment by 25huizengek1** [comment]
I haven't done anything to the codebase, the current release (v0.5.10) works perfectly fine on my end...

**Comment by tanmaytez** [comment]
> I haven't done anything to the codebase, the current release (v0.5.10) works perfectly fine on my end...

But I'm only able to get 77 songs from the playlist

I'm using ur forked 0.5.10 too

**Comment by 25huizengek1** [comment]
Which APK are you using? I recommend trying this with both versions available on [my F-Droid repo](https://github.com/25huizengek1/fdroid-repo) (add [this link](https://25huizengek1.github.io/fdroid-repo/fdroid/repo?fingerprint=A9F4730F35858B40CD7ED86E46030644120FB5DFBC1B3366D05CE38A7BDB5C79) to your F-Droid client to install)

What is the primary language that your device is using? And can you please you able to provide some logs of the loading of the playlist?

**Comment by tanmaytez** [comment]
> Which APK are you using? I recommend trying this with both versions available on [my F-Droid repo](https://github.com/25huizengek1/fdroid-repo) (add [this link](https://25huizengek1.github.io/fdroid-repo/fdroid/repo?fingerprint=A9F4730F35858B40CD7ED86E46030644120FB5DFBC1B3366D05CE38A7BDB5C79) to your F-Droid client to install)
> 
> What is the primary language that your device is using? And can you please you able to provide some logs of the loading of the playlist?

I can't open ur repo and the other link, it's showing me to scan a qr and still I can't access ur repo by scanning it.

The primary language is English and how can I provide playlist loading logs?
I've downloaded from here in ur repo

**Comment by 25huizengek1** [comment]
You have to add the URL's to an F-Droid client if you want nightly updates and regular releases downloaded automatically.

For now though it is enough to use the direct download links:
Latest release: https://github.com/25huizengek1/fdroid-repo/raw/master/fdroid/repo/it.vfsfitvnm.vimusic_26.apk
Nightly: https://github.com/25huizengek1/fdroid-repo/raw/master/fdroid/repo/it.vfsfitvnm.vimusic.nightly_20231210.apk

You can provide logs with either `adb logcat` (if you have a pc and know how Android Debug Bridge works) or install [Shizuku](https://shizuku.rikka.app/) and [Logfox](https://github.com/F0x1d/LogFox/releases/latest)

**Comment by tanmaytez** [comment]
I think I get it.

![Screenshot_2023-12-10-19-02-41-56_16951b262cae20e6c0b50d67c1f69074.jpg](https://github.com/25huizengek1/ViMusic/assets/132748284/da3a2b1f-199f-4cb6-8794-42284c38a379)

First I downloaded the nightly version and backed up vi music file and loaded the playlist, showed 77 songs

When I cleared the data and loaded the playlist.. it showed me 925 songs.

Actually I backed up the original vimusic file in ur vi music forked version and it somehow doesn't load playlist properly, i don't know what causes it.

Anyways I understood that I should use your forked version fresh and new and import playlists again.

**Comment by 25huizengek1** [comment]
That is not really the case. Adding the playlist on an old version of ViMusic 'synchronizes' it with your local database, and when you upgrade to a newer version it doesn't reload, that is where the 'sync' button in the hamburger menu below the playlist name is for. Only then the app will reload the playlist. This is mostly to save data traffic.

vfsfitvnm's original repository contained a bug that caused playlists not to load in it's entirety, so I think that is what caused this problem.

Anyways, I hope this helped, closing now as the issue has been resolved.
