### ISSUE TITLE
Downvote songs or stop them from playing again

### ISSUE THREAD

**Issue by devika15** [25huizengek1/ViMusic#32]
## Feature request: 

An ability to downvote songs that you don't like should be available so that the song doesn't play again when in autoplay mode or when you select a radio for similar songs. 

Thank you.

**Comment by 25huizengek1** [comment]
Good idea, but what do you mean with 'autoplay mode'?

**Comment by devika15** [comment]
Oh by autoplay mode I mean when you select "radio" from the song menu and
it automatically plays similar music. Often end up having to manually
remove a couple of songs that I don't like. So having a feature that skips
such songs  or doesn't add songs given a thumbs down to the playlist would
be great, thank you.

**Comment by Driftinginfinitely** [comment]
I would love this feature. Requested it on the original Vimusic but looks like that project has been paused indefinitely.

**Comment by 25huizengek1** [comment]
Implemented, available in the newest version and of couse in the nightly builds.

**Comment by devika15** [comment]
Thank you so much!!

**Comment by siggi1984** [comment]
Cool function👍
