### ISSUE TITLE
Search function in the playlists

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#44]
A search function in all playlists would be cool. To find the title you are looking for faster in playlists with 500+ songs and not scroll up and down for minutes

**Comment by 25huizengek1** [comment]
You don't have to scroll for minutes, because you can already search for songs?

**Comment by siggi1984** [comment]
> You don't have to scroll for minutes, because you can already search for songs?

Yes, that is correct, but it would be an advantage to search within the playlist where you are and not to switch back to the Songs tab.

**Comment by 25huizengek1** [comment]
I don't know why we would want this, I think this would only clutter the UI?

**Comment by siggi1984** [comment]
> I don't know why we would want this, I think this would only clutter the UI?

This is just a suggestion. In the end, you as the developer decide what to implement.

**Comment by 25huizengek1** [comment]
👍 

Closing this for now. If anyone has a suggestion on this, please let me know.
