### ISSUE TITLE
Hide Song (delete song) doesn't work in library mode

### ISSUE THREAD

**Issue by Enigma1309** [25huizengek1/ViMusic#46]
### Steps to reproduce the bug

When searching a song in library the hide song doesn't seem to work properly
This happens in following modes (as far as i know)
- Library (offline songs)
- My top X playlist

### Expected behavior

this should clear the cache of the song and remove it from listening history 

### Actual behavior

does nothing 

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/94917588/8ba25aa2-193f-4821-b836-0bbeb1f3a888

### ViMusic version

0.5.11

### Android version

Andorid 8.1

**Comment by 25huizengek1** [comment]
This is caused by the fact that there is no filter on total playtime anymore, but the hide feature still relies on that. Very strange I did not notice that.

**Comment by 25huizengek1** [comment]
Implemented a fix.
