### ISSUE TITLE
Swipe to change song in now playing 

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#5]
Would be cool if you could change the title on the "Now Playing" screen by swiping.

Swipe left on the cover image for the next song, swipe right for the previous song.

**Comment by 25huizengek1** [comment]
Will be included in v0.5.7, thanks for your suggestion.

**Comment by dtomvan** [comment]
Swiping left currently has the same behaviour as using the button, which means that swiping mid-song goes to the beginning instead of going to the previous song.

**Comment by 25huizengek1** [comment]
Subtle, but sure, for consistency this should be tweaked. Exoplayer's `seekToPrevious` "Seeks to an earlier position in the current or previous MediaItem (if available)", according to the documentation, so I think the most consistent way of handling this is by first seeking to `C.TIME_UNSET` of the current window, and then call `forceSeekToPrevious`. Will push when I have the time to. 

Thank you for your suggestion, reopening for now.

**Comment by 25huizengek1** [comment]
Thank you for pointing this out, will also be included in the next release.
