### ISSUE TITLE
queue button in mini player or hold down on mini player to go to queue

### ISSUE THREAD

**Issue by unclereeemus** [25huizengek1/ViMusic#50]
Hi,

Thanks for adding so many good features and making the app more useable. I have a suggestion:

As it is it takes too many motions to reach the queue so a dedicated button in the collapsed mini player or a motion like holding down on the mini player to go to queue would be appreciated

**Comment by 25huizengek1** [comment]
Thank you for your appreciation. Currently, when you click on the mini player, and then on the bottom queue bar, the queue opens. What is the problem exactly? Please elaborate a bit more on your idea.

**Comment by unclereeemus** [comment]
I personally would appreciate having to make as few motions as possible to get access to the queue. Like pulling up the mini player to get to the queue is a redundant motion in my mind + why not add this feature since pressing down on the mini player doesn't have any attached function now

**Comment by 25huizengek1** [comment]
I actually do not get what you are saying. You only need at most two taps to get to the queue. Tapping the player when it's minimized opens the player in full screen, with access to a lot more buttons, like sleep time, playback speed and so on.

What do you want me to make and where?

**Comment by unclereeemus** [comment]
I understand it's a niche complaint. I will close the issue; thanks for getting back
