### ISSUE TITLE
option to not start radio for songs automatically

### ISSUE THREAD

**Issue by unclereeemus** [25huizengek1/ViMusic#51]

**Comment by 25huizengek1** [comment]
What do you mean? Radio only starts playing when you explicitly click one of the radio buttons.

**Comment by 25huizengek1** [comment]
This is intended: when the song you've clicked on is not in some kind of list (playlist, album, etc.) the queue gets populated with similar songs. If you want only one song in the queue, you can just `Enqueue` the single song only.

There is no weirdness: this is intended behavior, and there is already a button to achieve what you are asking for.

**Comment by unclereeemus** [comment]
Oh nice! Did not think to do that. Thanks for clearing things up.
