### ISSUE TITLE
Artist cover image

### ISSUE THREAD

**Issue by brnwlshubh** [25huizengek1/ViMusic#57]
After adding any artist as favourite.
Artist is seen under Artist section.
After opening the artist the cover image is updated.

### Expected behavior

It should be updated automatically without opening.

### Actual behavior

It is updated after opening the artist page.

**Comment by 25huizengek1** [comment]
Not a bug. Why should you want this? This means your phone has to check periodically for a new artist image if I understand you correctly?

**Comment by brnwlshubh** [comment]
It was only my query if not bug then it's okay to as it is.

**Comment by brnwlshubh** [comment]
@25huizengek1 Is this can work only when I visit Artist tab and it updates that time?
