### ISSUE TITLE
Automatic backup function

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#58]
I know there is already a backup function, but an automatic backup function like Blackhole would be very useful or a scheduled, e.g. automatic backup once a day, it would also be cool if you could specify your cloud as the location for the backup file. In case you change your phone or tablet, it gets stolen or breaks, you would always have a backup file that you could restore.

**Comment by 25huizengek1** [comment]
You can already choose the could as the location of the backup file: in the file picker you can choose could storages like Google Drive in the side bar.

Now for the automatic backups: this is definitely possible but I do not know what kind of backup location would be ideal. Any suggestions?

**Comment by siggi1984** [comment]
The storage location for the backup file would have to be defined beforehand in the settings, e.g. a specific folder or cloud, and as soon as you have changed something, e.g. a playlist is created or a song is liked, a backup file should be created automatically in the previously defined location. Or simply automatically once a day, once a week, etc.,...

**Comment by 25huizengek1** [comment]
This is definitely possible, but what is the benefit in automatically saving to a local file? If your device gets stolen afterwards you'll still lose your data.

**Comment by siggi1984** [comment]
> This is definitely possible, but what is the benefit in automatically saving to a local file? If your device gets stolen afterwards you'll still lose your data.

In this case, it makes sense to select your cloud as the storage location.

**Comment by 25huizengek1** [comment]
Got it, but this means we'll have to integrate with multiple major cloud providers? Not sure about that one...

**Comment by 25huizengek1** [comment]
Maybe there is a FOSS solution?

**Comment by siggi1984** [comment]
> Maybe there is a FOSS solution?

Nextcloud or self-hosted Nextcloud?

**Comment by 25huizengek1** [comment]
I absolutely agree with this. If I were to implement this, it'll probably result in people 'missing' their cloud provider and we'll end up with a clusterfuck of login buttons and sync possibilities. For simplicity, anyone who even wants to backup anything can do it manually, or just rely on Piped. Closing this for now.

**Comment by dtomvan** [comment]
https://imgs.xkcd.com/comics/standards.png

**Comment by dtomvan** [comment]
![https://imgs.xkcd.com/comics/standards.png]
