### ISSUE TITLE
Create smart playlists 

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#6]
Creating smart playlists, i.e. you create a playlist with certain prerequisites and when listening to music, the songs are automatically added to the playlist when the prerequisites are met.

It's a bit difficult to explain, but I saw it on an offline player and thought it was a really cool feature.

If you like the idea you could have a look at it.
Suggested Solution

https://github.com/moritz-weber/mucke

**Comment by 25huizengek1** [comment]
Looks nice, don't know if we have enough metadata to work with (in mucke they use year, time added and like count for example), but definitely something to consider in the future.

**Comment by 25huizengek1** [comment]
Kinda thinking about labeling wontfix for a while, because I do not have a clear vision of how I want this to work (yet). Do you have an idea what to filter on for these smart playlists? @siggi1984

**Comment by siggi1984** [comment]
These are just a few examples: you could say, for example, that liked songs that have been listened to 3 times are added to the playlist, whereby the example number 3 should be a setting option. Or you could specify that only songs from a certain year are added, of course you would have to set the year or a year range, e.g. between 2000 and 2010.

It should be possible to set the number of songs to be included in the playlist.

The sorting in the playlist could possibly be set by number of playbacks or by artist name or song name, by year of release, since when in the library,

maybe there are other ideas that I can't think of right now.

**Comment by 25huizengek1** [comment]
Closing for now, as there is not enough metadata (e.g. year, like *count*) available right now to realise this with YouTube Music. Even if I were to implement it, I think it would result in a very inconsistent user experience, as most songs won't be included in said playlists.

If there are any new good ideas to realise this feature, then we can reopen and I'll of course consider it.
