### ISSUE TITLE
EDIT: SOLVED "App will not import database"

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#61]
### Steps to reproduce the bug

1. Go to settings to restore database
2. Pick the .db file

### Expected behavior

1. App should restart and install database 

### Actual behavior

2. No response: selecting the .db file exits the file manager and return to vimusic but nothing happens 
[vimusic_20240103152223.zip](https://github.com/25huizengek1/ViMusic/files/13827319/vimusic_20240103152223.zip)

### ViMusic version

V.0.6.2

### Android version

Android 10

### Additional information

The database I'm trying to import was exported from the classic vimusic app and 
I've attached the file as .zip

**Comment by brnwlshubh** [comment]
Working fine for me

**Comment by genericbetatester** [comment]
> Working fine for me

I tested it again it now works, reinstalling the app fixed it

**Comment by genericbetatester** [comment]
I used pre cache to restore my songs, OP feature :⁠-⁠D

**Comment by 25huizengek1** [comment]
I have no clue then what caused the issue. Reinstalling shouldn't have changed anything, but since it's fixed I'll close.
