### ISSUE TITLE
Music recommendations

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#63]
On Spotify, similar songs are recommended at the bottom of a created playlist, which can be added to the playlist with a + symbol. I would find such a function mega cool with ViMusic but I don't know if and to what extent something like this would be possible?

**Comment by 25huizengek1** [comment]
YouTube has support for this, kind of. You can only get recommendations for a certain video, or playlist (thats on YouTube (!), with possibly the current position in the playlist. So I can actually implement this in two ways:

1. This only works when playing a playlist that is *on* YouTube
2. The recommendations are based on the song that is currently playing.

**Comment by siggi1984** [comment]
> YouTube has support for this, kind of. You can only get recommendations for a certain video, or playlist (thats on YouTube (!), with possibly the current position in the playlist. So I can actually implement this in two ways:
> 
> 1. This only works when playing a playlist that is _on_ YouTube
> 2. The recommendations are based on the song that is currently playing.

That sounds pretty good. I'm curious.

**Comment by 25huizengek1** [comment]
I'd say we should only implement the second one for consistency?

**Comment by siggi1984** [comment]
> I'd say we should only implement the second one for consistency?

Yes, that sounds good.

**Comment by 25huizengek1** [comment]
Implemented, available in the next version 👍

**Comment by siggi1984** [comment]
Many thanks for implementing this function, it's mega cool.

Would it be possible to extend it a little. With a plus sign which you tap and then have the option to add the song to a specific playlist.

![Screenshot_20240119-163504_1](https://github.com/25huizengek1/ViMusic/assets/103368536/8c7db6a8-159e-4296-902a-0c552ea93ef3)

**Comment by 25huizengek1** [comment]
Already there, the extended menu is available, just click on the song.

**Comment by siggi1984** [comment]
> Already there, the extended menu is available, just click on the song.

Oh yes, I've seen it now too. Thanks for the hint.
