### ISSUE TITLE
added link to artist page 

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#7]
Clicking on the artist's name in the song player below the title should take you to the artist's page. Without the current detours.

![272187500-9fc63e06-4580-4d65-b4ba-ee5d891f0fda](https://github.com/25huizengek1/ViMusic/assets/103368536/3e94586a-943f-4da8-92d8-af1c31912419)

**Comment by 25huizengek1** [comment]
Nice touch, I like it. Thank you for your suggestion.

Will be included in the next release.

**Comment by siggi1984** [comment]
I don't know if it's related to this, but the artist name is now missing on some titles.

![Screenshot_20231116-174822](https://github.com/25huizengek1/ViMusic/assets/103368536/8591767c-1179-4ff0-b66a-9f558651a90b)

**Comment by 25huizengek1** [comment]
I was aware, already fixed it.

**Comment by 25huizengek1** [comment]
*in my local build, let me push it 😅 
Thank you for pointing this out
