### ISSUE TITLE
Difficulty in Sliding Gesture 

### ISSUE THREAD

**Issue by AbhiSharma096** [25huizengek1/ViMusic#71]
## Gesture optimisation 

I am experiencing it a bit uncomfortable to slide the quick piks section, I have to stretch my thumb all the way to left, it is quite good in YouTube music.

 Suggestions - maybe some tweaks in threshold limit of sliding works.

**Comment by Enigma1309** [comment]
discussed in #8, idk why it was closed though 🤔

**Comment by 25huizengek1** [comment]
Soo as far as I'm concerned the FlingBehavior does not have a 'threshold', but it can be adjusted, so I'll look into that later on.

Maybe the best fix is just using a different portion of the screen width as the width of a mood / quick pick? Currently it's defined (at least in portrait) as 90%.

**Comment by 25huizengek1** [comment]
I think this still looks nice, and is more user-friendly. Thank you for your suggestion, let me know if you have any further issues.
