### ISSUE TITLE
Ghost files showing up in local music 

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#72]
### Steps to reproduce the bug

Go to local music tab 

### Expected behavior

Only valid audio files should show up

### Actual behavior

Files with duration of 0.00s show up alongside real audio files 

### Screenshots/Screen recordings

![Screenshot_20240114-135534](https://github.com/25huizengek1/ViMusic/assets/140274753/524bcc37-b018-4d25-b7a3-8ce965a65179)

### ViMusic version

v0.6.2

### Android version

Android 10 

### Additional information

I seem to be facing a unique issue, but does anyone have any ideas on how to resolve it? Perhaps @25huizengek1 could implement a filter to prevent short-duration audio files from appearing, maybe those less than 5 seconds. This is just a suggestion. I attempted to scan the internal storage, but I couldn't locate any files with the tags displayed in the player. I also tried a different music player, but it didn't identify any similar files.

**Comment by 25huizengek1** [comment]
What are the extensions of those files? I can of course implement a filter but I want to investigate first.

**Comment by genericbetatester** [comment]
> What are the extensions of those files? I can of course implement a filter but I want to investigate first.

I can't see the files in a file manager so I don't know where it's stored or what it is but here is the full name 
![Screenshot_20240115-051338](https://github.com/25huizengek1/ViMusic/assets/140274753/d0cd3887-1337-45dd-9747-c621481df86d)

**Comment by 25huizengek1** [comment]
I think this fixed it. Please let me know if you have any further issues.

**Comment by genericbetatester** [comment]
> I think this fixed it. Please let me know if you have any further issues.

That is fast. Thank you very much
