### ISSUE TITLE
Crash while pre-caching for first time

### ISSUE THREAD

**Issue by th3y** [25huizengek1/ViMusic#75]
### Steps to reproduce the bug

1-Fresh(clean) install
2-Open app
3-Hold song item and choose 'Pre cache'

### Expected behavior

Precache song and keep using the app

### Actual behavior

Crash

### ViMusic version

V.6.0.2

### Android version

Android 10

### Additional information

Crash could be avoid if you listen the song, wait a 2-1 second and press 'pre-cache'
Crash cant be reproduced if there's already precached song
You can also crash the app if you dont wait 1-2 seconds while playing the song and press 'precache' fast

**Comment by 25huizengek1** [comment]
That seems odd, though the code crashes explicitly (https://github.com/25huizengek1/ViMusic/blob/master/app/src/main/kotlin/it/vfsfitvnm/vimusic/service/PrecacheService.kt#L112) when the cache is not initialized, which seems like what’s going on here.

**Comment by 25huizengek1** [comment]
I can't reproduce this myself. Can you please provide some logs for me to investigate further?

**Comment by th3y** [comment]
Is this ok?
[crash_precachefirsttime.txt](https://github.com/25huizengek1/ViMusic/files/13965174/crash_precachefirsttime.txt)

**Comment by 25huizengek1** [comment]
Yes, those look great, fixed it. If any issues persist, please let me know.
