### ISSUE TITLE
Video Search Not Working

### ISSUE THREAD

**Issue by anxiouslelimo** [25huizengek1/ViMusic#76]
### Steps to reproduce the bug

1. Search for the terms abhi, abhi na jao, tere mere etc
2. Go to videos section

### Expected behavior

The videos should show

### Actual behavior

No video

### ViMusic version

v0.6.2

### Android version

11

**Comment by 25huizengek1** [comment]
It seems like YouTube changed some stuff in their internal API’s. I’ll get back to this later.

**Comment by 25huizengek1** [comment]
Actually, the search filter for video’s is not even in the official UI anymore, so maybe this tab needs to be removed as well. If this is the case we can always use YouTube instead of YouTube Music though.

**Comment by 25huizengek1** [comment]
Can you please provide a screenshot of this happening? Does it show an error or just no results?

**Comment by genericbetatester** [comment]
> Actually, the search filter for video’s is not even in the official UI anymore, so maybe this tab needs to be removed as well. If this is the case we can always use YouTube instead of YouTube Music though.

I would much like it if we used YouTube instead of YT music instead.

**Comment by 25huizengek1** [comment]
Fixed in db625cb5685f3ae6799716ae23b9c3ed866c8863
