### ISSUE TITLE
No Featured Playlist in Search

### ISSUE THREAD

**Issue by anxiouslelimo** [25huizengek1/ViMusic#78]
### Steps to reproduce the bug

1. Search for pop, rock etc

### Expected behavior

Featured Playlist should be shown in search results

### Actual behavior

No Featured Playlist shown

### ViMusic version

v0.6.2

### Android version

11

**Comment by 25huizengek1** [comment]
Not a bug: got replaced by ‘Discover’, and is not officially supported by YouTube anymore.

**Comment by 25huizengek1** [comment]
There is still ‘recommended’ playlists though, I can add that If you want.

**Comment by 25huizengek1** [comment]
> There is still ‘recommended’ playlists though, I can add that If you want.

I just remembered why I removed it initially: ViMusic still uses version 1.20220918 of Innertube (YouTube), so some stuff is just not accurate anymore, including the recommended playlists.

**Comment by 25huizengek1** [comment]
> https://youtube.com/playlist?list=RDCLAK5uy_k6CicQMBYujmwL9DB5xBripE9EfgeKpHM https://youtube.com/playlist?list=RDCLAK5uy_nmS3YoxSwVVQk9lEQJ0UX4ZCjXsW_psU8

Thank you. I'll try to fix this. It seems like YouTube handles it a bit differently than what I initially expected.

**Comment by 25huizengek1** [comment]
> > There is still ‘recommended’ playlists though, I can add that If you want.
> 
> I just remembered why I removed it initially: ViMusic still uses version 1.20220918 of Innertube (YouTube), so some stuff is just not accurate anymore, including the recommended playlists.

Won't add it, at least for now I think, because there are only a few working keywords so the Discover tab should suffice.
