### ISSUE TITLE
Suggested UI changes for the bottom navigation section of "now playing" screen (new layout)

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#79]
## Feature request: [Suggested UI changes for the bottom navigation section of "now playing" screen (new layout)]

I'd like to propose some minor changes to the bottom navigation bar layout. Specifically, I suggest the following:

- Moving the "playback speed" button inside the "options" tab: Currently, the playback speed button is placed beside the "options"button which creates an uneven layout. Moving it inside the options tab would allow for uncluttered UI and more balanced layout.

- Replacing the "song loop on/off" text with the classic song loop icon: The current use of text for the song loop button is inconsistent with the other icons in the navigation bar. Replacing it with an icon would make the UI more streamlined 

![20240117_183105~2](https://github.com/25huizengek1/ViMusic/assets/140274753/520ee9a9-bd71-4a7b-9994-76f328e08095)

Here's a prototype of what the new layout could look like:

![Graphic1](https://github.com/25huizengek1/ViMusic/assets/140274753/f8570bda-794b-4e7e-a4f8-aa88a6665399)

I believe these changes would improve UI consistency and aesthetics. I'd like to hear your opinions too. Thanks for your consideration!

**Comment by genericbetatester** [comment]
> yeah, that looks more refined and simple.

Thanks

**Comment by 25huizengek1** [comment]
That seems like a good idea. It unclutters the UI a bit, so I think I'll implement it.

**Comment by 25huizengek1** [comment]
Implemented, available in the next version.

**Comment by genericbetatester** [comment]
> Implemented, available in the next version.

Hi @25huizengek1 , I just wanted to say a huge thank you for implementing the feature so quickly. I really appreciate your hard work and dedication, and I'm impressed by how quickly you were able to make the changes. Keep up the great work!

**Comment by 25huizengek1** [comment]
No problem, thank you for your appreciation. I have a great passion for good software and use this app daily, so my goal is to improve the user experience (and slowly but surely improve the codebase, some stuff is still more cluttered than it needs to be)
