### ISSUE TITLE
Lack of scrolling smoothness in Quick Pick section

### ISSUE THREAD

**Issue by dainvincible1** [25huizengek1/ViMusic#8]
### Steps to reproduce the bug

Scroll quick picks

### Expected behavior

scrolling should be smooth

### Actual behavior

scrolling is not smooth

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/127825700/f33c254a-255c-4ec5-9375-bfeacf96e84c

### ViMusic version

latest version

### Android version

android 11

**Comment by 25huizengek1** [comment]
How exactly is this a bug? It's actually intended behavior, it uses snap flingbehavior and animates between the grid columns to the nearest one after you release your finger from the screen.

**Comment by dainvincible1** [comment]
> How exactly is this a bug? It's actually intended behavior, it uses snap flingbehavior and animates between the grid columns to the nearest one after you release your finger from the screen.

there was only two option feature and bug. its not a feature request so i put the bug label. Thanks for clarifying 👍

**Comment by Enigma1309** [comment]
Is there any way to decrease the threshold of this? cause on small screens it's quite annoying.
