### ISSUE TITLE
Related albums and others won't show up

### ISSUE THREAD

**Issue by tanmaytez** [25huizengek1/ViMusic#83]
When the app is launched, some suggestions like related albums or playlists wouldn't display, making it the blank area. I have tried force stopping the app and still it won't fix.

![Screenshot_2024-01-19-11-40-19-27_6f55a3c4de83481ebdee1685416eed82.jpg](https://github.com/25huizengek1/ViMusic/assets/132748284/43a644cc-5f8d-40b5-b7fc-06bd0e8af048)

**Comment by 25huizengek1** [comment]
Don’t know if you closed by accident, but just for your information: YouTube doesn’t provide all Quick Picks with some songs, so they are just not available in this case. You can try changing the quick picks source in the settings

**Comment by tanmaytez** [comment]
> Don’t know if you closed by accident, but just for your information: YouTube doesn’t provide all Quick Picks with some songs, so they are just not available in this case. You can try changing the quick picks source in the settings

I have actually opened another one closing this
