### ISSUE TITLE
App crashes when moving last song on queue upward

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#87]
### Steps to reproduce the bug

The bug is easily reproducible. Simply create a queue of songs, and then try to drag the last song upward in the list. The app crashes consistently when I attempt this action.

### Expected behavior

I should simply be able to move the songs anyhow I want it.

### Actual behavior

But the app crashes consistently when I attempt this action.

### Screenshots/Screen recordings

https://github.com/25huizengek1/ViMusic/assets/140274753/756aaa4e-1064-408a-b16b-a8fcf233356e

### ViMusic version

v.0.6.2

### Android version

Android 10

**Comment by 25huizengek1** [comment]
It may surprise you, but this is actually the same problem as #68, so I'll continue to track the issue in there.

**Comment by genericbetatester** [comment]
> It may surprise you, but this is actually the same problem as #68, so I'll continue to track the issue in there.

Alright then
