### ISSUE TITLE
Unfortunately, update 0.6.3 didn't fix playlist issue

### ISSUE THREAD

**Issue by genericbetatester** [25huizengek1/ViMusic#88]
### Steps to reproduce the bug

FIRST ISSUE 
1. Move any song any song in the queue 
downwards

SECOND ISSUE
1.Move the last song from the bottom of the playlist upwards 

### Expected behavior

FIRST ISSUE 
The song new position should be saved

SECOND ISSUE
Song should move upwards/change position normally 

### Actual behavior

FIRST ISSUE
It doesn't get saved, it just gives blank space and resets to initial position.

SECOND ISSUE
This time around, app doesn't crash, the song just freezes then disappears from queue completely.

### ViMusic version

v.0.6.3

### Android version

Android 10

### Additional information

The new update didn't fix the issue(at least for me)

**Comment by ardumiguel** [comment]
I really think this is not the version the developer mentioned included the fix. You should test it installing the nightly build

**Comment by 25huizengek1** [comment]
Aware of all of them, fixed all of them, tracking in #68, please let me know in there so we can reopen, no build from my part is yet released, so the fix is not included in 0.6.3.

**Comment by genericbetatester** [comment]
> I really think this is not the version the developer mentioned included the fix. You should test it installing the nightly build

I didn't know, I'll try that

**Comment by 25huizengek1** [comment]
Just FYI, the build just went through: https://github.com/25huizengek1/fdroid-repo/blob/master/fdroid/repo/it.vfsfitvnm.vimusic.nightly_20240124.apk
