### ISSUE TITLE
Clear music queue

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#9]
Ability to remove the entire song queue instead of individual songs. Could be implemented as a button in the bottom bar of the playlist manager

**Comment by 25huizengek1** [comment]
This has already been implemented. If you weren't aware, you can just swipe down the player from the bottom of your screen to clear the queue and stop playing.

**Comment by dtomvan** [comment]
> you can just swipe down the player from the bottom of your screen

Yes, and let's also support android's one-handed mode gesture (which is a swipe down from near the bottom of the screen) by adding swiping to the side (ie left or right).

**Comment by 25huizengek1** [comment]
Seems like a good idea for better accesibility, I'll put it behind a preference tho, because for people not using one-handed mode it may not make sense, pushing in a bit...

**Comment by 25huizengek1** [comment]
Will be included in the next release (v0.5.8)

**Comment by 25huizengek1** [comment]
If you are curious, here's what it looks like right now. Now that I think of it I might have to tweak the animation a bit, but we'll see.

https://github.com/25huizengek1/ViMusic/assets/50515369/6501a959-1bd0-4e02-8b2b-a708050d18a8
