### ISSUE TITLE
A small change to the Now Playing screen

### ISSUE THREAD

**Issue by DavidRLTG** [25huizengek1/ViMusic#94]
## Feature request: A small Now Playing redesign

Not a perfectionist, But there's a tiny issue with the Now Playing screen that _really_ rubs me the wrong way!

The way the play/pause button gets rounded is opposite to the Android Music notification
Here, I have some screenshots:
![Screenshot_20240127-154325](https://github.com/25huizengek1/ViMusic/assets/87834635/56d5a1b2-9feb-416e-83ce-a87200387fea)
![Screenshot_20240127-154343](https://github.com/25huizengek1/ViMusic/assets/87834635/f412d5ff-05b4-4826-a5c4-319254fd51d2)
![Screenshot_20240127-154436](https://github.com/25huizengek1/ViMusic/assets/87834635/8394a995-612a-4a16-a883-5e9ce97b361f)
![Screenshot_20240127-154502](https://github.com/25huizengek1/ViMusic/assets/87834635/1c745f81-f0d5-47f4-a2dc-900e81be5a36)

It really rubs me the wrong way, haha
Could the animation be reversed, So that the now playing screen looks more like Android itself? Thank you!

Another thing, the Now Playing screen looks similar to the one shown in the Android 12: Designed for You youtube video.
Maybe you could get it to look _even more_ like it? Just a suggestion, really.
![Screenshot_20240127-154618](https://github.com/25huizengek1/ViMusic/assets/87834635/0a07718a-2ba9-4d0c-a028-47538b183538)

Thanks for reading! I hope my suggestion helps.

**Comment by dtomvan** [comment]
> Not a perfectionist

Hmm, I believe this is a very minor nitpick, but maybe consistency with your specific android ROM could be included. Don't know how it would work with the current design vision of ViMusic though.

**Comment by DavidRLTG** [comment]
I'm on GrapheneOS, so basically AOSP, no skins.
This is how it looks like on official android so haha

**Comment by dtomvan** [comment]
Yes, but a bunch of vendors (Samsung, Xiaomi, Huawei, some Motorola's and OnePlus) change the theming of the system UI, so I'll consider ViMusic's theme independent of whatever your ROM is doing...

**Comment by DavidRLTG** [comment]
Ohhh, True.
But I'm pretty sure getting it consistent across all ROM's is pretty much technically Impossible

I mean come on, this isn't Linux with GTK.

**Comment by dtomvan** [comment]
That said, I understand your concern, so I think a small patch could be made so you could compile your own vimusic player behaviour. But that doesn't mean the player should be radically changed imho. I am in favour of some more theming options in ViMusic though. But considering the way ViMusic's UI is implemented, refactoring it all to Material You for example, would be a hassle...

**Comment by dtomvan** [comment]
> I mean come on, this isn't Linux with GTK.

Funny you mention that. Linux is the utmost inconsistent with UI. Think of QT, Kvantum, the 3 different major versions of GTK in use currently on a modern desktop, gtk theme engines etc.

**Comment by DavidRLTG** [comment]
Oh I understand, but ViMusic is still 99% Material3/Material You, right?

So getting the player to be more fitting doesn't sound like a bad idea, IMO

**Comment by DavidRLTG** [comment]
> > I mean come on, this isn't Linux with GTK.
> 
> Funny you mention that. Linux is the utmost inconsistent with UI. Think of QT, Kvantum, the 3 different major versions of GTK in use currently on a modern desktop, gtk theme engines etc.

No? I mean, my Linux setup is completely consistent, i don't see your point. I use XFCE, my theme is in most apps I install.

**Comment by dtomvan** [comment]
> Oh I understand, but ViMusic is still 99% Material3/Material You, right?

You'd be surprised. ViMusic is almost entirely independent of Material3. On the contrary, I'd estimate that just 1 percent of the UI is Material3. I don't remember exactly, but I vaguely recall *a single* usage of Material3...

**Comment by DavidRLTG** [comment]
> > Oh I understand, but ViMusic is still 99% Material3/Material You, right?
> 
> You'd be surprised. ViMusic is almost entirely independent of Material3. On the contrary, I'd estimate that just 1 percent of the UI is Material3. I don't remember exactly, but I vaguely recall _a single_ usage of Material3...

Surprising..
Well, I dunno if I'm blind, but most of the app does seem to follow Material You design except a few differences.
That's just how I see it, though!

**Comment by dtomvan** [comment]
First off, I don't want to keep debating on this off-topic subject matter, but one more comment:
> my theme

This is the culprit. Your theme might be working for you quite well, but that doesn't mean it's consistent across all user interfaces. Even apps like Steam/Discord run their own static theme, so strictly UI won't ever be entirely consistent. That said it's getting better and better with time, but the linux desktop is just unnecessarily complicated...

**Comment by DavidRLTG** [comment]
> First off, I don't want to keep debating on this off-topic subject matter, but one more comment:
> 
> > my theme
> 
> This is the culprit. Your theme might be working for you quite well, but that doesn't mean it's consistent across all user interfaces. Even apps like Steam/Discord run their own static theme, so strictly UI won't ever be entirely consistent. That said it's getting better and better with time, but the linux desktop is just unnecessarily complicated...

Yeah, talking about this is offtopic but aye, one last answer-

Of course it won't be consistent everywhere! Apps these days are mostly web based anyways, it's insane
Besides,
_Windows is like 10 times worse so_

And aye, you finding it complicated is fine, I just personally understand it and all

**Comment by 25huizengek1** [comment]
Maybe you're right, this is also how most M3 apps handle this. A good example is Google's calculator app, all buttons are less rounded when they are activated. And while ViMusic doesn't really follow Material Design guidelines and doesn't implement Material You (we only (re)use a few components from Material, and map the components individually to our own styles), it's still a good design principle and for consistency's sake we could swap these values.

I don't think we have to put this in Appearance settings, do we?

**Comment by DavidRLTG** [comment]
> Maybe you're right, this is also how most M3 apps handle this. A good example is Google's calculator app, all buttons are less rounded when they are activated. And while ViMusic doesn't really follow Material Design guidelines and doesn't implement Material You (we only (re)use a few components from Material, and map the components individually to our own styles), it's still a good design principle and for consistency's sake we could swap these values.
> 
> I don't think we have to put this in Appearance settings, do we?

I dunno!
But I'm glad that we agree,
This could make ViMusic more consistent with Android (or well, AOSP.)

By the way, out of curiosity, Will ViMusic ever be redesigned to follow Material Design principles, or will it remain as it is? A curious question, is all.

**Comment by 25huizengek1** [comment]
I actually have not a single clue of what I should do with the design of the app. I kinda like the way ViMusic has it's own design, while still maintaining a clear and consistent UI, but at the same time it may be an interesting idea to actually rebuild most of the UI. This is definitely not unfeasible, as ViMusic already uses some of Material's principles/looks and is not *entirely* different from Material. Interesting idea overall.

**Comment by DavidRLTG** [comment]
Thank You! I find the idea interesting, too
Before ViMusic ceased development, I even suggested a few design ideas to the ViMusic Github, funny enough
Two got approved, but only one made it in the final app.

I am actually the guy who led to the Lyrics being moved on top of the album cover instead of being a separate button 😂

It was my idea, Hopefully it was a good design choice

**Comment by 25huizengek1** [comment]
Great, nice to know! I also think it was a good choice, it makes the navigation inside of the player way clearer, though it was a pain to implement the swiping behavior, as there are many gestures to account for: tapping, long pressing, scrolling, and now 'scrolling horizontally'. In the end, it was all worth it though, I think the album cover behaves in a simple but useful way right now.

**Comment by DavidRLTG** [comment]
Thank you! And haha yeah, I understand. Programming in general is a true pain
Hence why I'm a tech nerd who basically knows tech in and out and studied every aspect of it, but just CANNOT learn to code and cannot understand it. It's so hard and boring to me 😭
Good luck with development on this fork, friendo

**Comment by 25huizengek1** [comment]
That's a pity, but I understand it: building an application can be quite complicated and overwhelming.

No problem, I try to strive for good software (though the codebase needs some refactoring, as vfsfitvnm actually pointed out as well, so I'm slowly but surely restructuring the codebase), while not overcomplicating things and providing a nice user experience.

This is especially important for me personally, because I actually daily-drive this app now 😂 (fun fact: this started out as a private patch, as described in b80b38dd759130b8eaa4d191fb3ad20bfcafdde0)

**Comment by DavidRLTG** [comment]
Haha, Nice! I'm really glad that you made this Fork, because, well uh

_Most other music streaming apps on F-Droid are really really bloated and slow_
And the only other ViMusic fork is RiMusic.

_**which is insanely slow and bloated too**_

So this really helped me 😭
I daily drive this app too, I legit refused to switch from ViMusic even if it was abandoned. Thank god that this exists

**Comment by 25huizengek1** [comment]
Thank you! I love it that you recognize this. This fork actually exists a bit shorter than RiMusic, so RiMusic still tends to get a lot more attention. I think it's a shame that their codebase tends to get cluttered with a lot of useless stuff (and they take some code from this codebase as well).

I just want to be a worthy continuation of ViMusic, while competing with apps like RiMusic. I'm actually going to rebrand soon (but I deliberately do not want to remove a lot of traces of the original app and developer, vfsfitvnm, in contrast what RiMusic did as a consequence of their rebranding) to `ViTune`, so maybe since you are so involved with this fork, I still need a new icon/logo for the app. I've looked at this so far: https://github.com/vfsfitvnm/ViMusic/issues/1434 and I'm curious what 'my users' (wow that probably sounds a bit too grande) think of something like that icon.

I understand you 😂, as I said the only reason I decided to even start hacking on this app is because of the exact same frustration with the current state of music streaming.

**Comment by DavidRLTG** [comment]
Hell yeah! Well, I'm so glad that uh.. You exist and you made this xd
And hey, That icon looks very great, IMO!
I could take a shot at trying to design my own icon as well, but it'd probably be worse considering my previous designs 😂

_I barely make any anyway-_

But yes, that icon looks great! I support it.

Oh and of course, forgot to say,
You're welcome! (You said Thank You and I can't be impolite xD)
It's awkward to talk in Github issues, but definitely wholesome to get along with the developer on a random issue 👍

**Comment by 25huizengek1** [comment]
Great, I'll take this in consideration.

While we're definitely off-topic, I don't mind the fact that this in issues, I like this conversation as well! If you want to contact me through email though: development@vitune.app

**Comment by 25huizengek1** [comment]
Auto-closed in above commit, it looks like this now:

![image](https://github.com/25huizengek1/ViMusic/assets/50515369/0a62c401-5a0c-431c-ad05-c01e74df9934)

**Comment by DavidRLTG** [comment]
Haha, Thank you, My E-Mail is davidrltg@protonmail.com if you ever need me (for some reason) as well. Thanks for the nice talk!

and hey, cool new design! 👍

**Comment by 25huizengek1** [comment]
No problem man, please let me know when there are any concerns in the future.

The new design is entirely thanks to @Colorata's (dead) fork of ViMusic, [Guitarist](https://github.com/Colorata/Guitarist), so I won't take credit for that 😄

**Comment by DavidRLTG** [comment]
Hmm! On the note of concerns, suggestions, all that-
Two more notes I'd like to leave here!
1. I also have the weird lyrics animation bug seen in another issue here!
2. A tiny change, but one that would really help a lot, Could we have an option that makes the Local tab ONLY show songs from the /sdcard/Music folder? So this way it doesn't find a ton of random audio files and recordings 😂

and aahhh I see heh
Well, their design is pretty cool!
It looks similar to the Android 12 Presentation video design (as seen in the screenshot at the top of the issue) which I REALLY like, makes it feel more like a system app of sorts. Cool stuff!
