### ISSUE TITLE
Smart Recommendations 

### ISSUE THREAD

**Issue by siggi1984** [25huizengek1/ViMusic#97]
Would it be possible to add a function like Spotify that occasionally adds similar songs to the playlists to discover them as you listen?
So the songs should not be added to the playlist, but simply to the current playback.

We already have a similar function. Perhaps the new function could simply add songs from the existing function (see screenshot) as soon as you have activated it.

![Screenshot_20240127-210815](https://github.com/25huizengek1/ViMusic/assets/103368536/e158bff9-4730-4b60-a2a4-f885df59257e)

Spotify has this button in the playlists to activate the function. See screenshot.
![signal-2024-01-27-21-22-17-131_1](https://github.com/25huizengek1/ViMusic/assets/103368536/c850a787-1776-42c3-83d1-6fb65b404e27)

**Comment by dtomvan** [comment]
Considering how Innertube and YTM work this would only be possible for playlists that also exist on the platform in question. This would make the feature inconsistent with itself.

**Comment by 25huizengek1** [comment]
Don't think I have to add anything here: this is exactly how I look at it. Closing for now, unless there are some good ideas on how we want to tackle this problem. In that case, please let me know.
