### ISSUE TITLE
Full screen lyrics

### ISSUE THREAD

**Issue by Syntax-Err5** [25huizengek1/ViMusic#98]
## Feature request: Add the option to show song lyrics in full screen

Hi, I'd like to request the addition of full screen lyrics similar to apps like Tidal and Apple Music (see images). 

Tidal:
![lyrics-phone 9669ce9](https://github.com/25huizengek1/ViMusic/assets/123362106/a2dbd1e7-89e6-45b5-baf2-0913655f94ee)

Apple Music:
![Screenshot_2024-01-28-10-58-42-26_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/25huizengek1/ViMusic/assets/123362106/c8788bbf-1cda-4b97-8fc8-c3a99c844e86)

It could be enabled with another button in the lyrics overlay (see image) or through an option in Settings > Appearance.
![Screenshot_2024-01-28-11-19-55-60_6f55a3c4de83481ebdee1685416eed82~2](https://github.com/25huizengek1/ViMusic/assets/123362106/58cc03b4-20f9-4937-97d9-7c372f9aaa56)

Thank you for considering, I'm really loving this ViMusic fork!

**Comment by 25huizengek1** [comment]
Great idea. I'll implement this when I have the time to.

**Comment by 25huizengek1** [comment]
Added in the above commit. I was aware that RiMusic had had this feature, implemented it a bit different though: the lyrics enlarge when you pinch to zoom

**Comment by 25huizengek1** [comment]
<img width="30%" src="https://github.com/25huizengek1/ViMusic/assets/50515369/9ceab597-0125-4e1d-93a3-86a5d3f32bd0" />

It looks like this.
