### ISSUE TITLE
Change package ID

### ISSUE THREAD

**Issue by 1xFF** [25huizengek1/ViMusic#99]
## Feature request: [Change package ID so that the app can be installed separately from ViMusic]

I'd like to try this fork out, but as I currently use the original ViMusic, I can't install it due to it still having the "it.vfsfitvnm.vimusic" app ID

I see that the main page has "vitune.app" in the readme, if this fork will be renamed to that, it should be done sooner rather then later as changing the ID will require old installation's database to be exported.

Or even just your username replacing vfsfitvnm's like: com.25huizengek1.vimusic

**Comment by dtomvan** [comment]
You could use some nightly build to get a different package name or even use a tool like [ApkTool M](https://maximoff.su/apktool/?lang=en) to resign and rename the package yourself. The nightly build can be found on [GitHub](https://github.com/25huizengek1/fdroid-repo/blob/master/fdroid/repo/it.vfsfitvnm.vimusic.nightly_20240127.apk) or [F-Droid](https://25huizengek1.github.io/fdroid-repo/fdroid/repo/).

Note: the project will be rebranded soon though, so stay tuned for that.

**Comment by 25huizengek1** [comment]
Thank you @dtomvan for providing this information. We'll change the application ID after the rebranding to something like `app.vitune`.

For now the nightly build is a great alternative to already try out the application. This is not always a stable version though, as it builds the master branch almost daily.

As far as the progress on the rebranding, I'm still looking through options for a new logo, and after that I can carry on with finalizing everything. Please be patient as I try to come up with something that works for me. I'd suggest continuing this conversation the discussion though (#54), so I'll close this.

**Comment by 1xFF** [comment]
Great thank you both, the nightly build works great.
I was going to link the suggested icon for ViMusic which vfsfitvnm turned down, but it seems you've already found that 😅
